const translations = {
  fr: {
    title: "Hugo Jasmin - Portfolio",
    subtitle: "Étudiant en ingénierie logicielle à IMT Atlantique",
    about: "À propos",
    skills: "Compétences",
    experience: "Expérience",
    projects: "Projets",
    contact: "Contact",
    education: "Formation",
    languages: "Langues",
    activities: "Activités",
    about_text: "Étudiant en ingénierie des systèmes d'information à IMT Atlantique, passionné par le développement logiciel collaboratif et les technologies web.",
    footer: "© 2025 Hugo Jasmin. Tous droits réservés.",
    nav_back: "← Retour au menu principal",
    project_movieapp_title: "Webapp de notation de films",
    project_movieapp_desc: "Application inspirée d’IMDb réalisée avec Flask, HTML, Jinja, JavaScript et CSS.",
    project_bnp_title: "Accessibilité pour BNP Paribas",
    project_bnp_desc: "Optimisation de l’accessibilité selon le RGAA avec HTML, CSS et JavaScript.",
    project_innovation_title: "Projet Innovation Durable",
    project_innovation_desc: "Conception d’un transport rural durable via enquêtes terrain, prototypage et outils Lean Startup.",
    lang_en: "Anglais",
    lang_en_level: "Courant",
    lang_de: "Allemand",
    lang_de_level: "A2 (compréhension orale), B1 (compréhension écrite, expression écrite et orale) - Certifié DSD1",
    exp_unisphere_title: "Développeur Front-end (Stage) - Unisphere GmbH",
    exp_unisphere_date: "Avril 2025 – Août 2025 | Constance, Allemagne",
    exp_unisphere_desc: "Développement de modules de simulation de vol avec VueJS, TypeScript et NodeJS dans une équipe Agile internationale.",
    exp_junior_title: "Responsable Qualité - Junior Atlantique",
    exp_junior_date: "Octobre 2023 – Décembre 2024 | Nantes",
    exp_junior_desc: "Encadrement du système qualité, audits internes, conformité CNJE, structuration RSE et formalisation de processus internes.",
    edu_imt_desc: "Formation d'ingénieur généraliste",
    edu_faidherbe_desc: "Classe Préparatoire aux grandes écoles : PCSI - PSI* - Travail de recherche (TIPE) sur le transport d'électricité par induction",
    edu_branly_desc: "Baccalauréat général, spécialités Mathématiques, Physique-chimie - Mention très bien avec les félicitations du jury",
    activity_music_title: "Musique",
    activity_music_desc: "12 ans de pratique de la clarinette - Certificat d'études musicales obtenu au Conservatoire à Rayonnement Régional d'Amiens Métropole (2020)",
    activity_sport_title: "Sport",
    activity_sport_desc1: "Cyclisme et course à pied",
    activity_sport_desc2: "Pratique en club : judo (5 ans), football (4 ans), triathlon (1 an)"
  },
  en: {
    title: "Hugo Jasmin - Portfolio",
    subtitle: "Software engineering student at IMT Atlantique",
    about: "About",
    skills: "Skills",
    experience: "Experience",
    projects: "Projects",
    contact: "Contact",
    education: "Education",
    languages: "Languages",
    activities: "Activities",
    about_text: "Software engineering student at IMT Atlantique, passionate about collaborative development and web technologies.",
    footer: "© 2025 Hugo Jasmin. All rights reserved.",
    nav_back: "← Back to main menu",
    project_movieapp_title: "Movie Rating Webapp",
    project_movieapp_desc: "IMDb-inspired application built with Flask, HTML, Jinja, JavaScript, and CSS.",
    project_bnp_title: "Accessibility for BNP Paribas",
    project_bnp_desc: "Accessibility optimization according to RGAA with HTML, CSS, and JavaScript.",
    project_innovation_title: "Sustainable Innovation Project",
    project_innovation_desc: "Design of sustainable rural transport via field surveys, prototyping, and Lean Startup tools.",
    lang_en: "English",
    lang_en_level: "Fluent",
    lang_de: "German",
    lang_de_level: "A2 (spoken comprehension), B1 (written comprehension, written and spoken expression) - Certified DSD1",
    exp_unisphere_title: "Front-end Developer (Intern) - Unisphere GmbH",
    exp_unisphere_date: "April 2025 – August 2025 | Constance, Germany",
    exp_unisphere_desc: "Development of flight simulation modules with VueJS, TypeScript, and NodeJS in an international Agile team.",
    exp_junior_title: "Quality Manager - Junior Atlantique",
    exp_junior_date: "October 2023 – December 2024 | Nantes",
    exp_junior_desc: "Management of the quality system, internal audits, CNJE compliance, CSR structuring, and internal process formalization.",
    edu_imt_desc: "General engineering training",
    edu_faidherbe_desc: "Preparatory class for grandes écoles: PCSI - PSI* - Research project (TIPE) on electricity transport by induction",
    edu_branly_desc: "General baccalaureate, specialties Mathematics, Physics-chemistry - Honors mention with congratulations from the jury",
    activity_music_title: "Music",
    activity_music_desc: "12 years of clarinet practice - Certificate of musical studies obtained at the Conservatoire à Rayonnement Régional d'Amiens Métropole (2020)",
    activity_sport_title: "Sports",
    activity_sport_desc1: "Cycling and running",
    activity_sport_desc2: "Club practice: judo (5 years), football (4 years), triathlon (1 year)"
  },
  de: {
    title: "Hugo Jasmin - Portfolio",
    subtitle: "Informatikstudent an der IMT Atlantique",
    about: "Über mich",
    skills: "Fähigkeiten",
    experience: "Erfahrung",
    projects: "Projekte",
    contact: "Kontakt",
    education: "Ausbildung",
    languages: "Sprachen",
    activities: "Aktivitäten",
    about_text: "Informatikstudent an der IMT Atlantique, begeistert von kollaborativer Softwareentwicklung und Webtechnologien.",
    footer: "© 2025 Hugo Jasmin. Alle Rechte vorbehalten.",
    nav_back: "← Zurück zum Hauptmenü",
    project_movieapp_title: "Film-Bewertungs-Webapp",
    project_movieapp_desc: "Von IMDb inspirierte Anwendung, erstellt mit Flask, HTML, Jinja, JavaScript und CSS.",
    project_bnp_title: "Barrierefreiheit für BNP Paribas",
    project_bnp_desc: "Optimierung der Barrierefreiheit gemäß RGAA mit HTML, CSS und JavaScript.",
    project_innovation_title: "Projekt für nachhaltige Innovation",
    project_innovation_desc: "Entwicklung eines nachhaltigen ländlichen Transports durch Felduntersuchungen, Prototyping und Lean Startup-Tools.",
    lang_en: "Englisch",
    lang_en_level: "Fließend",
    lang_de: "Deutsch",
    lang_de_level: "A2 (hörverstehen), B1 (schriftliches Verständnis, schriftlicher und mündlicher Ausdruck) - Zertifiziert DSD1",
    exp_unisphere_title: "Front-end Entwickler (Praktikum) - Unisphere GmbH",
    exp_unisphere_date: "April 2025 – August 2025 | Konstanz, Deutschland",
    exp_unisphere_desc: "Entwicklung von FlugSimulationsmodulen mit VueJS, TypeScript und NodeJS in einem internationalen Agile-Team.",
    exp_junior_title: "Qualitätsmanager - Junior Atlantique",
    exp_junior_date: "Oktober 2023 – Dezember 2024 | Nantes",
    exp_junior_desc: "Leitung des Qualitätsmanagementsystems, interne Audits, CNJE-Konformität, CSR-Strukturierung und Formalisierung interner Prozesse.",
    edu_imt_desc: "Allgemeine Ingenieurausbildung",
    edu_faidherbe_desc: "Vorbereitungsklasse für grandes écoles: PCSI - PSI* - Forschungsprojekt (TIPE) über den Transport von Elektrizität durch Induktion",
    edu_branly_desc: "Allgemeines Abitur, Spezialitäten Mathematik, Physik-Chemie - Auszeichnung mit sehr gutem Ergebnis und Lob des Prüfungsausschusses",
    activity_music_title: "Musik",
    activity_music_desc: "12 Jahre Klarinettenpraxis - Zertifikat für musikalische Studien am Conservatoire à Rayonnement Régional d'Amiens Métropole (2020)",
    activity_sport_title: "Sport",
    activity_sport_desc1: "Radfahren und Laufen",
    activity_sport_desc2: "Vereinsaktivitäten: Judo (5 Jahre), Fußball (4 Jahre), Triathlon (1 Jahr)"
  }
};
